export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const GET_HEADER = "GET_HEADER";
export const GET_PROFILE = "GET_PROFILE";
export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING";
export const SET_ISLASTPAGE_PROFILE = "SET_ISLASTPAGE_PROFILE";
export const GET_REPOS = "GET_REPOS";
export const NO_REPOS = "NO_REPOS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const RESOLVE_INVITE = "RESOLVE_INVITE";
export const GET_PROFILEIDS = "GET_PROFILEIDS";
export const GET_PROFILES = "GET_PROFILES";
export const GET_MORE_PROFILES = "GET_MORE_PROFILES";
export const SET_ISLASTPAGE_PROFILES = "SET_ISLASTPAGE_PROFILES";
export const SET_PROFILES_LOADING = "SET_PROFILES_LOADING";
export const CLEAR_PROFILELIST = "CLEAR_PROFILELIST";
export const PROFILES_ERROR = "PROFILES_ERROR";
export const NO_PROFILES_FOUND = "NO_PROFILES_FOUND";


export const GET_POSTS = "GET_POSTS";
export const UPDATE_NUM_OF_COMMENTS = "UPDATE_NUM_OF_COMMENTS";
export const NO_POSTS_FOUND = "NO_POSTS_FOUND";
export const GET_MORE_POSTS = "GET_MORE_POSTS";
export const SET_POST_LOADING = "SET_POST_LOADING";
export const SET_ISLASTPAGE_POST = "SET_ISLASTPAGE_POST";
export const CLEAR_POSTS = "CLEAR_POSTS";
export const GET_POSTIDS = "GET_POSTIDS";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";

export const ADD_COMMENT = "ADD_COMMENT";
export const SET_ISLASTPAGE_COMMENT = "SET_ISLASTPAGE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const SET_COMMENT_LOADING = "SET_COMMENT_LOADING";
export const UPDATE_LIKE_FOR_POST = "UPDATE_LIKE_FOR_POST";
export const UPDATE_COMMENTLIKES = "UPDATE_COMMENTLIKES";
export const GET_POST = "GET_POST";
export const GET_COMMENTIDS = "GET_COMMENTIDS";
export const GET_COMMENTS = "GET_COMMENTS";
export const GET_MORE_COMMENTS = "GET_MORE_COMMENTS";
export const CLEAR_COMMENTS = "CLEAR_COMMENTS";
export const COMMENT_ERROR = "COMMENT_ERROR";






